### ISSUE TITLE
Port Townsend inference system container crashes

### ISSUE THREAD

**Issue by micya** [orcasound/aifororcas-livesystem#76]
Port Townsend inference system container (orcaconservancycr.azurecr.io/live-inference-system:11-15-20.FastAI.R1-12.PortTownsend.v0) crashes with the below message:

```
Listening to location https://s3-us-west-2.amazonaws.com/streaming-orcasound-net/rpi_port_townsend
Traceback (most recent call last):
  File "./src/LiveInferenceOrchestrator.py", line 158, in <module>
    clip_path, start_timestamp, current_clip_end_time = hls_stream.get_next_clip(current_clip_end_time)
  File "/usr/src/app/src/hls_utils/HLSStream.py", line 94, in get_next_clip
    num_segments_in_wav_duration = math.ceil(self.polling_interval/stream_obj.target_duration)
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
```

**Comment by prakruti** [comment]
Port Townsend hydrophone is currently offline. Please check https://live.orcasound.net/port-townsend
